### PR TITLE
Add property advertising-clause to indiana-extreme license.

### PR DESCRIPTION
**Pull request by willebra**

### CODE REVIEW

**Review by mmurto — COMMENTED** [review]
Is this really an advertisement clause, rather than requirement for inclusion in notice file? I assume section 3 is the one considered:

```
3. The end-user documentation included with the redistribution, if any, must include the following acknowledgment:

"This product includes software developed by the Indiana University Extreme! Lab (http://www.extreme.indiana.edu/)."

Alternately, this acknowledgment may appear in the software itself, if and wherever such third-party acknowledgments normally appear.
```

**Comment by Toniprni** [comment]
@mmurto you're right, the license we're discussing doesn't have an advertising clause, just a standard attribution requirement for documentation. However, we've mistakenly applied the "advertising clause" label to similar licenses like Apache-1.1 in the past (or to be exact I have). These, along with the license at hand, only require attribution in documentation. True advertising clauses, as seen in licenses like Apache-1.0 and BSD-4-Clause, mandate attribution in advertising materials.

**Comment by willebra** [comment]
The Apache-1.1 includes, according to our classification, an advertising clause. The corresponding text is: 
`3. The end-user documentation included with the redistribution, if any, must include the following acknowledgment:
"This product includes software developed by the Apache Software Foundation (http://www.apache.org/)."
Alternately, this acknowledgment may appear in the software itself, if and wherever such third-party acknowledgments normally appear. `
So the indiana extreme -license has quite identical text and therefore these both should be treated in a similar way. Apache-1.1 contains, as per general undestanding, a wider notice/advertising requirement than the Apache-2.0 (while being less than Apache-1.0).

On the other hand, it might be useful to consider moving Apache-1.1 outside of the advertising clause. It would be easier for compliance. Looking at how we describe the notice requirement in license classification versus the advertising requirement, there could be room for it already now. The gist would be that if the requirement can be fulfilled by notice reproduction (and it can be considered to be end-user documentation), then it would not be an advertising clause. Considering our current client cases, itheir notice practices would seem to fulfil the notice requirement in Apache-1.1.

This means, however, that mere reproduction of software code would not be sufficient to fufill all notice requirements. E.g. the MIT license has:
`The above copyright notice and this permission notice (including the next paragraph) shall be included in all copies or substantial portions of the Software.`
Which does not require a separate notice, and giving the client access to the source code arguably, and as per our practice, fulfils this requirement. Now, if we mix MIT-style notice requirements with Apache-1.1 style, we will loose this distinction.

For completeness here is a pure advertising-clause (BSD-4-clause, however, this has been given up, but this is still a representative example): 
`all advertising materials mentioning features or use of this software display the following acknowledgement:
"This product includes software developed by the University of California, Lawrence Berkeley Laboratory and its contributors.''`

I wonder, should we acutually have three levels of notice requirements? Ping @sschuberth

**Comment by sschuberth** [comment]
> I wonder, should we acutually have three levels of notice requirements? Ping @sschuberth

Whatever you guys deem necessary / meaningful to distinguish is fine with me. On the ORT level, it might be that we fulfill multiple of these obligations in the same way (e.g. by making source code available), but have fine-grained classifications here certainly is a good thing to be prepared for future use-cases.

**Comment by mmurto** [comment]
> The Apache-1.1 includes, according to our classification, an advertising clause. The corresponding text is: `3. The end-user documentation included with the redistribution, if any, must include the following acknowledgment: "This product includes software developed by the Apache Software Foundation (http://www.apache.org/)." Alternately, this acknowledgment may appear in the software itself, if and wherever such third-party acknowledgments normally appear. ` So the indiana extreme -license has quite identical text and therefore these both should be treated in a similar way. Apache-1.1 contains, as per general undestanding, a wider notice/advertising requirement than the Apache-2.0 (while being less than Apache-1.0).

I'd say classification of Apache-1.1 and others like that could be modified then. We discussed with Martin, and while the obligations may differ somewhat (MIT-style requirement being fulfilled by distributing the source code, Apache-1.1 maybe not), best practice is to create and distribute a notice wile within the end-user documentation, which fulfills both.

So my suggestion is to have one property (include-in-notice-file), which includes all of these, and the guidance for using it is that those licenses should be, ahem... _included in notice file_ and the file distributed.

**Comment by willebra** [comment]
> I'd say classification of Apache-1.1 and others like that could be modified then. We discussed with Martin, and while the obligations may differ somewhat (MIT-style requirement being fulfilled by distributing the source code, Apache-1.1 maybe not), best practice is to create and distribute a notice wile within the end-user documentation, which fulfills both. So my suggestion is to have one property (include-in-notice-file), which includes all of these, and the guidance for using it is that those licenses should be, ahem... included in notice file and the file distributed.

Let's keep it simple for now, we will handle MIT and Apache-1.1 type notice requirements with the `property:include-in-notice-file` and we could still separate those later, if client needs arise. So this PR should be closed.

**Pull request closed without merging**
